logging:
  level:
    ROOT: debug
    cn.zhangxd.oak: debug

spring:
  profiles:
    active: dev
    include: swagger
  jackson:
    serialization.indent_output: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: localhost
      port: 8500
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

jasypt:
  encryptor:
    password: fg1YAyCQHHU52xdA

server:
  port: 9999

oak:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization"
    allow-credentials: true
    max-age: 1800
  security:
    client-authorization:
      client-id: internal
      client-secret: internal
  mail: # specific Oak mail property, for standard properties see MailProperties
    from: oakservice@163.com
    base-url: http://127.0.0.1:9999

uaa:
  key-store:
    name: keystore.jks
    password: password
    alias: selfsigned
  web-client-configuration:
    # Access Token is valid for 5 mins
    access-token-validity-in-seconds: 300
    # Refresh Token is valid for 7 days
    refresh-token-validity-in-seconds-for-remember-me: 604800
    client-id: web_app
    secret: changeit
