feign:
  hystrix:
    enabled: true

hystrix:
  share-security-context: true

management:
  security:
    roles: ADMIN
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
  application:
    name: uaa
  cloud:
    consul:
      discovery:
        healthCheckPath: /management/health
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    favicon:
      enabled: false
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3

info:
  project:
    version: #project.version#

oak:
  swagger:
    default-include-pattern: /api/.*
    title: UAA API
    description: uaa API documentation
    version: ${info.project.version}
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
